[2024-11-12T04:33:03.361+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T04:33:03.392+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-12T04:32:58.669558+00:00 [queued]>
[2024-11-12T04:33:03.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-12T04:32:58.669558+00:00 [queued]>
[2024-11-12T04:33:03.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T04:33:03.418+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgBenef> on 2024-11-12 04:32:58.669558+00:00
[2024-11-12T04:33:03.425+0000] {standard_task_runner.py:63} INFO - Started process 43417 to run task
[2024-11-12T04:33:03.429+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgBenef', 'manual__2024-11-12T04:32:58.669558+00:00', '--job-id', '708', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmp4mdi6cti']
[2024-11-12T04:33:03.430+0000] {standard_task_runner.py:91} INFO - Job 708: Subtask load_data_to_stgBenef
[2024-11-12T04:33:03.492+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-12T04:32:58.669558+00:00 [running]> on host 3d0ab7361361
[2024-11-12T04:33:03.897+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgBenef' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T04:32:58.669558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T04:32:58.669558+00:00'
[2024-11-12T04:33:03.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T04:33:03.972+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-12T04:33:13.946+0000] {logging_mixin.py:188} INFO - Error fetching data from API: 500 Server Error: Internal Server Error for url: http://host.docker.internal:8000/benef
[2024-11-12T04:33:14.015+0000] {logging_mixin.py:188} INFO - Không có dữ liệu để chèn.
[2024-11-12T04:33:14.068+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T04:33:14.148+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T04:33:14.227+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_data_to_stgBenef, run_id=manual__2024-11-12T04:32:58.669558+00:00, execution_date=20241112T043258, start_date=20241112T043303, end_date=20241112T043314
[2024-11-12T04:33:14.357+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T04:33:14.372+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
