[2024-11-06T03:33:27.717+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-06T03:33:27.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-06T03:32:59.241246+00:00 [queued]>
[2024-11-06T03:33:27.749+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-06T03:32:59.241246+00:00 [queued]>
[2024-11-06T03:33:27.750+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-06T03:33:27.761+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_stgBenef> on 2024-11-06 03:32:59.241246+00:00
[2024-11-06T03:33:27.766+0000] {standard_task_runner.py:63} INFO - Started process 17487 to run task
[2024-11-06T03:33:27.769+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_data_to_stgBenef', 'manual__2024-11-06T03:32:59.241246+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpwaavfzf6']
[2024-11-06T03:33:27.770+0000] {standard_task_runner.py:91} INFO - Job 465: Subtask load_data_to_stgBenef
[2024-11-06T03:33:27.806+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_data_to_stgBenef manual__2024-11-06T03:32:59.241246+00:00 [running]> on host 3d0ab7361361
[2024-11-06T03:33:28.047+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_data_to_stgBenef' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T03:32:59.241246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T03:32:59.241246+00:00'
[2024-11-06T03:33:28.048+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-06T03:33:28.089+0000] {logging_mixin.py:188} INFO - Kết nối đến MySQL thành công
[2024-11-06T03:33:49.122+0000] {logging_mixin.py:188} INFO - Error fetching data from API: 500 Server Error: Internal Server Error for url: http://host.docker.internal:8000/benef
[2024-11-06T03:33:49.123+0000] {logging_mixin.py:188} INFO - Không có dữ liệu để chèn.
[2024-11-06T03:33:49.125+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-06T03:33:49.126+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-06T03:33:49.139+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=load_data_to_stgBenef, run_id=manual__2024-11-06T03:32:59.241246+00:00, execution_date=20241106T033259, start_date=20241106T033327, end_date=20241106T033349
[2024-11-06T03:33:49.194+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-06T03:33:49.422+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-06T03:33:49.424+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
